from database.db import SessionLocal, create_tables
from models.models import Question, CompanyQuestion

QUANT = [
    {"category":"quantitative","difficulty":"easy","question_text":"A train travels 360 km in 4 hours. Speed in km/h?","options":["80","90","100","110"],"correct_answer":"90","explanation":"Speed = 360/4 = 90 km/h","tags":["speed"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Shopkeeper sells at 20% profit. CP=500. Selling price?","options":["550","580","600","620"],"correct_answer":"600","explanation":"SP = 500 x 1.20 = 600","tags":["profit-loss"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Item bought for 800 sold at 680. Loss percentage?","options":["12%","15%","17%","20%"],"correct_answer":"15%","explanation":"Loss% = 120/800 x 100 = 15%","tags":["profit-loss"]},
    {"category":"quantitative","difficulty":"easy","question_text":"What is 15% of 480?","options":["62","68","72","75"],"correct_answer":"72","explanation":"480 x 15/100 = 72","tags":["percentages"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Price increased 20% then decreased 20%. Net change?","options":["-4%","0%","+4%","-2%"],"correct_answer":"-4%","explanation":"100 -> 120 -> 96. Net = -4%","tags":["percentages"]},
    {"category":"quantitative","difficulty":"easy","question_text":"30% of what number is 90?","options":["270","280","300","320"],"correct_answer":"300","explanation":"x x 30/100 = 90 -> x = 300","tags":["percentages"]},
    {"category":"quantitative","difficulty":"easy","question_text":"SI on 8000 at 5% per annum for 3 years?","options":["1000","1100","1200","1300"],"correct_answer":"1200","explanation":"SI = 8000x5x3/100 = 1200","tags":["simple-interest"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Sum doubles in 10 years at SI. Rate of interest?","options":["8%","9%","10%","12%"],"correct_answer":"10%","explanation":"P = PxRx10/100 -> R = 10%","tags":["simple-interest"]},
    {"category":"quantitative","difficulty":"medium","question_text":"CI on 10000 at 10% per annum for 2 years?","options":["2000","2100","2200","2500"],"correct_answer":"2100","explanation":"CI = 10000[(1.1)^2 - 1] = 2100","tags":["compound-interest"]},
    {"category":"quantitative","difficulty":"easy","question_text":"6 workers complete job in 8 days. Workers needed in 3 days?","options":["14","16","18","20"],"correct_answer":"16","explanation":"6x8 = xx3 -> x = 16","tags":["work-time"]},
    {"category":"quantitative","difficulty":"medium","question_text":"A does work in 10 days, B in 15 days. Together?","options":["5 days","6 days","7 days","8 days"],"correct_answer":"6 days","explanation":"1/10 + 1/15 = 1/6. Time = 6 days","tags":["work-time"]},
    {"category":"quantitative","difficulty":"easy","question_text":"Ratio A:B = 3:5. If B = 45, find A?","options":["25","27","30","32"],"correct_answer":"27","explanation":"A/45 = 3/5 -> A = 27","tags":["ratio"]},
    {"category":"quantitative","difficulty":"easy","question_text":"Average of 5 numbers is 27. Excluding one, avg = 25. Excluded number?","options":["30","33","35","37"],"correct_answer":"35","explanation":"Sum5=135. Sum4=100. Excluded=35","tags":["averages"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Average of 10 numbers = 20. Each multiplied by 3. New average?","options":["23","40","60","80"],"correct_answer":"60","explanation":"Average triples = 20x3 = 60","tags":["averages"]},
    {"category":"quantitative","difficulty":"hard","question_text":"Average age of 30 students = 14. Teacher joins, avg = 15. Teacher's age?","options":["40","41","44","45"],"correct_answer":"45","explanation":"31x15 - 30x14 = 465 - 420 = 45","tags":["averages"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Boat speed 15 km/h, stream 3 km/h. Upstream speed?","options":["10","12","13","18"],"correct_answer":"12","explanation":"Upstream = 15 - 3 = 12 km/h","tags":["boats"]},
    {"category":"quantitative","difficulty":"easy","question_text":"LCM of 12 and 18?","options":["24","36","48","72"],"correct_answer":"36","explanation":"LCM(12,18) = 36","tags":["number-system"]},
    {"category":"quantitative","difficulty":"easy","question_text":"Sum of first 50 natural numbers?","options":["1225","1275","1325","1375"],"correct_answer":"1275","explanation":"50x51/2 = 1275","tags":["number-system"]},
    {"category":"quantitative","difficulty":"easy","question_text":"Area of circle radius 7cm? (pi=22/7)","options":["150","154","158","162"],"correct_answer":"154","explanation":"22/7 x 49 = 154 cm2","tags":["mensuration"]},
    {"category":"quantitative","difficulty":"easy","question_text":"Perimeter of rectangle l=12cm, b=8cm?","options":["36","40","42","48"],"correct_answer":"40","explanation":"2(12+8) = 40 cm","tags":["mensuration"]},
    {"category":"quantitative","difficulty":"easy","question_text":"A die thrown. Probability of getting a prime number?","options":["1/2","1/3","2/3","1/6"],"correct_answer":"1/2","explanation":"Primes: 2,3,5. P = 3/6 = 1/2","tags":["probability"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Bag: 5 red, 3 blue, 2 green balls. P(red)?","options":["1/2","3/10","1/3","2/5"],"correct_answer":"1/2","explanation":"P(red) = 5/10 = 1/2","tags":["probability"]},
    {"category":"quantitative","difficulty":"medium","question_text":"5 people arranged in a row. How many ways?","options":["60","100","120","240"],"correct_answer":"120","explanation":"5! = 120","tags":["permutation"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Committee of 3 from 8. How many ways?","options":["56","112","168","336"],"correct_answer":"56","explanation":"C(8,3) = 56","tags":["combination"]},
    {"category":"quantitative","difficulty":"easy","question_text":"If 3x + 7 = 22, find x?","options":["4","5","6","7"],"correct_answer":"5","explanation":"3x = 15 -> x = 5","tags":["algebra"]},
    {"category":"quantitative","difficulty":"hard","question_text":"Pipe A fills in 30 min, B empties in 40 min. Both open. Time to fill?","options":["100 min","110 min","120 min","130 min"],"correct_answer":"120 min","explanation":"1/30 - 1/40 = 1/120. Time = 120 min","tags":["pipes"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Angle between clock hands at 3:30?","options":["60 deg","65 deg","75 deg","80 deg"],"correct_answer":"75 deg","explanation":"Hour=105 deg, minute=180 deg. Diff=75 deg","tags":["clocks"]},
    {"category":"quantitative","difficulty":"hard","question_text":"A sells to B at 10% profit, B to C at 10%. C pays 121. A's cost price?","options":["90","95","100","110"],"correct_answer":"100","explanation":"CPx1.1x1.1 = 121 -> CP = 100","tags":["profit-loss"]},
    {"category":"quantitative","difficulty":"hard","question_text":"CI minus SI on 5000 at 8% for 2 years?","options":["28","32","40","50"],"correct_answer":"32","explanation":"SI=800, CI=832. Diff=32","tags":["interest"]},
    {"category":"quantitative","difficulty":"medium","question_text":"Pipes A and B fill tank in 12 and 16 hrs. Both open. Time?","options":["6.5 hr","6.86 hr","7 hr","7.5 hr"],"correct_answer":"6.86 hr","explanation":"7/48. Time = 48/7 = 6.86 hr","tags":["pipes"]},
]

LOGICAL = [
    {"category":"logical","difficulty":"easy","question_text":"2, 6, 12, 20, 30, ?","options":["40","42","44","46"],"correct_answer":"42","explanation":"Differences 4,6,8,10,12. Next = 42","tags":["series"]},
    {"category":"logical","difficulty":"easy","question_text":"1, 4, 9, 16, 25, ?","options":["30","36","42","49"],"correct_answer":"36","explanation":"Perfect squares. 6^2 = 36","tags":["series"]},
    {"category":"logical","difficulty":"medium","question_text":"3, 9, 27, 81, ?","options":["162","243","324","189"],"correct_answer":"243","explanation":"x3 each time. 81x3 = 243","tags":["series"]},
    {"category":"logical","difficulty":"medium","question_text":"1, 1, 2, 3, 5, 8, 13, ?","options":["19","20","21","22"],"correct_answer":"21","explanation":"Fibonacci: 8+13 = 21","tags":["series"]},
    {"category":"logical","difficulty":"hard","question_text":"2, 3, 5, 9, 17, 33, ?","options":["60","65","67","70"],"correct_answer":"65","explanation":"x2-1 pattern. 33x2-1 = 65","tags":["series"]},
    {"category":"logical","difficulty":"easy","question_text":"100, 96, 88, 72, ?","options":["40","42","44","56"],"correct_answer":"40","explanation":"Diffs double: 4,8,16,32. 72-32=40","tags":["series"]},
    {"category":"logical","difficulty":"easy","question_text":"Odd one out: 2, 3, 5, 7, 9, 11","options":["2","9","11","5"],"correct_answer":"9","explanation":"9 = 3x3, not prime. All others are prime","tags":["odd-one-out"]},
    {"category":"logical","difficulty":"easy","question_text":"Odd one out: Apple, Mango, Banana, Potato, Orange","options":["Apple","Banana","Potato","Orange"],"correct_answer":"Potato","explanation":"Potato is vegetable; others are fruits","tags":["odd-one-out"]},
    {"category":"logical","difficulty":"medium","question_text":"Odd one out: 121, 169, 196, 225, 290","options":["121","196","225","290"],"correct_answer":"290","explanation":"All others are perfect squares","tags":["odd-one-out"]},
    {"category":"logical","difficulty":"easy","question_text":"All roses are flowers. All flowers are plants. Conclusion?","options":["True","False","Uncertain","Cannot say"],"correct_answer":"True","explanation":"Transitive: roses -> flowers -> plants","tags":["syllogisms"]},
    {"category":"logical","difficulty":"medium","question_text":"Some cats are dogs. All dogs are animals. Which is definitely true?","options":["All cats animals","Some cats animals","All animals dogs","No cats animals"],"correct_answer":"Some cats animals","explanation":"Some cats -> dogs -> animals","tags":["syllogisms"]},
    {"category":"logical","difficulty":"easy","question_text":"Row of 40. Priya is 11th from left. Position from right?","options":["28th","29th","30th","31st"],"correct_answer":"30th","explanation":"40 - 11 + 1 = 30","tags":["ranking"]},
    {"category":"logical","difficulty":"medium","question_text":"Ravi is 7th from left and 8th from right. Total in row?","options":["13","14","15","16"],"correct_answer":"14","explanation":"7 + 8 - 1 = 14","tags":["ranking"]},
    {"category":"logical","difficulty":"easy","question_text":"Ram walks 5km North, right 3km, right 5km. How far from start?","options":["3km East","3km West","3km North","3km South"],"correct_answer":"3km East","explanation":"N5, E3, S5 -> net 3km East","tags":["directions"]},
    {"category":"logical","difficulty":"easy","question_text":"Book : Library :: Painting : ?","options":["Artist","Canvas","Gallery","Museum"],"correct_answer":"Gallery","explanation":"Books in Library; Paintings in Gallery","tags":["analogies"]},
    {"category":"logical","difficulty":"easy","question_text":"Doctor : Hospital :: Teacher : ?","options":["Study","School","Student","Classroom"],"correct_answer":"School","explanation":"Doctor in Hospital; Teacher in School","tags":["analogies"]},
    {"category":"logical","difficulty":"easy","question_text":"COLD : WARM as NIGHT : ?","options":["Dark","Day","Moon","Stars"],"correct_answer":"Day","explanation":"Opposites: COLD-WARM, NIGHT-DAY","tags":["analogies"]},
    {"category":"logical","difficulty":"medium","question_text":"A is B's sister. C is B's mother. D is C's father. A related to D?","options":["Granddaughter","Daughter","Grandmother","Niece"],"correct_answer":"Granddaughter","explanation":"D is A's grandfather","tags":["blood-relations"]},
    {"category":"logical","difficulty":"medium","question_text":"Ravi is 16th from top in class of 40. Rank from bottom?","options":["23","24","25","26"],"correct_answer":"25","explanation":"40 - 16 + 1 = 25","tags":["ranking"]},
    {"category":"logical","difficulty":"medium","question_text":"Angle between clock hands at 4:20?","options":["0 deg","5 deg","10 deg","15 deg"],"correct_answer":"10 deg","explanation":"Minute=120 deg, Hour=130 deg, Diff=10 deg","tags":["clocks"]},
    {"category":"logical","difficulty":"easy","question_text":"7, 14, 28, 56, ?","options":["96","100","112","120"],"correct_answer":"112","explanation":"x2 each. 56x2 = 112","tags":["series"]},
    {"category":"logical","difficulty":"easy","question_text":"Odd one out: Pen, Pencil, Eraser, Sharpener, Book","options":["Pen","Pencil","Book","Eraser"],"correct_answer":"Book","explanation":"Book is not a writing instrument","tags":["odd-one-out"]},
    {"category":"logical","difficulty":"medium","question_text":"A faces East, turns 90 degrees clockwise, then 180 degrees. Direction now?","options":["North","South","East","West"],"correct_answer":"North","explanation":"East -> South (90CW) -> North (180)","tags":["directions"]},
    {"category":"logical","difficulty":"medium","question_text":"Employees who worked overtime got bonus. Ravi got no bonus. So?","options":["Ravi worked overtime","Ravi did not work overtime","Ravi not eligible","Ravi absent"],"correct_answer":"Ravi did not work overtime","explanation":"Contrapositive: no bonus -> no overtime","tags":["reasoning"]},
    {"category":"logical","difficulty":"hard","question_text":"P implies Q, Q implies R. Which must be true?","options":["R implies P","P implies R","Q implies P","R implies Q"],"correct_answer":"P implies R","explanation":"P->Q->R, so P->R by transitivity","tags":["reasoning"]},
    {"category":"logical","difficulty":"medium","question_text":"Pattern: AZ, BY, CX, DW, ?","options":["EV","EU","FV","EW"],"correct_answer":"EV","explanation":"Forward + backward alphabet","tags":["pattern"]},
    {"category":"logical","difficulty":"medium","question_text":"Some chairs are tables. All tables wooden. Some chairs wooden?","options":["Yes follows","No","Cannot say","Partial"],"correct_answer":"Yes follows","explanation":"Some chairs -> tables -> wooden","tags":["syllogisms"]},
    {"category":"logical","difficulty":"medium","question_text":"A is father of C. B is mother of D. C and D siblings. A related to B?","options":["Father","Husband","Brother","Uncle"],"correct_answer":"Husband","explanation":"A(father) + B(mother) = same children","tags":["blood-relations"]},
    {"category":"logical","difficulty":"hard","question_text":"Matrix: 2,4,8 | 3,9,27 | 4,16,?","options":["32","48","64","128"],"correct_answer":"64","explanation":"n, n^2, n^3. Row3: 4, 16, 64","tags":["pattern"]},
    {"category":"logical","difficulty":"medium","question_text":"ACEG : BDFH :: PRTV : ?","options":["QSUW","QSTU","RSUW","QRST"],"correct_answer":"QSUW","explanation":"Add 1 to each letter","tags":["analogies"]},
]

CODING = [
    {"category":"coding","difficulty":"easy","question_text":"## Reverse a String\nReturn the reverse of the input string.\n\n**Input:** hello\n**Output:** olleh","correct_answer":"","starter_code":"s = input()\n\ndef reverse_string(s):\n    # Write your solution here\n    pass\n\nprint(reverse_string(s))","test_cases":[{"input":"hello","expected":"olleh"},{"input":"placement","expected":"tnemecalp"},{"input":"abcde","expected":"edcba"}],"tags":["strings","easy"]},
    {"category":"coding","difficulty":"easy","question_text":"## Check Palindrome\nPrint True if palindrome else False.\n\n**Input:** racecar\n**Output:** True","correct_answer":"","starter_code":"s = input().strip()\n\ndef is_palindrome(s):\n    # Write your solution here\n    pass\n\nprint(is_palindrome(s))","test_cases":[{"input":"racecar","expected":"True"},{"input":"hello","expected":"False"},{"input":"madam","expected":"True"}],"tags":["strings","easy"]},
    {"category":"coding","difficulty":"easy","question_text":"## Sum of Digits\nFind sum of all digits.\n\n**Input:** 123\n**Output:** 6","correct_answer":"","starter_code":"n = input().strip()\n\ndef sum_of_digits(n):\n    # Write your solution here\n    pass\n\nprint(sum_of_digits(n))","test_cases":[{"input":"123","expected":"6"},{"input":"9999","expected":"36"},{"input":"100","expected":"1"}],"tags":["math","easy"]},
    {"category":"coding","difficulty":"easy","question_text":"## Count Vowels\nCount vowels (a,e,i,o,u) case-insensitive.\n\n**Input:** Hello World\n**Output:** 3","correct_answer":"","starter_code":"s = input()\n\ndef count_vowels(s):\n    # Write your solution here\n    pass\n\nprint(count_vowels(s))","test_cases":[{"input":"Hello World","expected":"3"},{"input":"Python","expected":"1"},{"input":"AEIOU","expected":"5"}],"tags":["strings","easy"]},
    {"category":"coding","difficulty":"medium","question_text":"## Factorial\nFind factorial of N.\n\n**Input:** 5\n**Output:** 120","correct_answer":"","starter_code":"n = int(input())\n\ndef factorial(n):\n    # Write your solution here\n    pass\n\nprint(factorial(n))","test_cases":[{"input":"5","expected":"120"},{"input":"0","expected":"1"},{"input":"10","expected":"3628800"}],"tags":["recursion","medium"]},
    {"category":"coding","difficulty":"medium","question_text":"## Fibonacci Series\nPrint first N Fibonacci numbers space-separated.\n\n**Input:** 7\n**Output:** 0 1 1 2 3 5 8","correct_answer":"","starter_code":"n = int(input())\n\ndef fibonacci(n):\n    # Write your solution here\n    pass\n\nprint(*fibonacci(n))","test_cases":[{"input":"7","expected":"0 1 1 2 3 5 8"},{"input":"1","expected":"0"},{"input":"5","expected":"0 1 1 2 3"}],"tags":["dp","medium"]},
    {"category":"coding","difficulty":"medium","question_text":"## Two Sum\nFind indices of two numbers that add to target.\nLine 1: integers, Line 2: target\n\n**Input:** 2 7 11 15 / 9\n**Output:** 0 1","correct_answer":"","starter_code":"nums = list(map(int, input().split()))\ntarget = int(input())\n\ndef two_sum(nums, target):\n    # Write your solution here\n    pass\n\nr = two_sum(nums, target)\nprint(r[0], r[1])","test_cases":[{"input":"2 7 11 15\n9","expected":"0 1"},{"input":"3 2 4\n6","expected":"1 2"}],"tags":["arrays","medium"]},
    {"category":"coding","difficulty":"medium","question_text":"## Prime Check\nCheck if N is prime. Print True or False.\n\n**Input:** 17\n**Output:** True","correct_answer":"","starter_code":"n = int(input())\n\ndef is_prime(n):\n    # Write your solution here\n    pass\n\nprint(is_prime(n))","test_cases":[{"input":"17","expected":"True"},{"input":"4","expected":"False"},{"input":"2","expected":"True"}],"tags":["math","medium"]},
    {"category":"coding","difficulty":"hard","question_text":"## Binary Search\nReturn index if found, -1 if not.\nLine 1: sorted integers, Line 2: target\n\n**Input:** 1 3 5 7 9 / 7\n**Output:** 3","correct_answer":"","starter_code":"arr = list(map(int, input().split()))\ntarget = int(input())\n\ndef binary_search(arr, target):\n    # Write your solution here\n    pass\n\nprint(binary_search(arr, target))","test_cases":[{"input":"1 3 5 7 9\n7","expected":"3"},{"input":"1 3 5 7 9\n6","expected":"-1"},{"input":"2 4 6 8\n2","expected":"0"}],"tags":["searching","hard"]},
    {"category":"coding","difficulty":"hard","question_text":"## Maximum Subarray (Kadane's)\nFind maximum sum of a contiguous subarray.\n\n**Input:** -2 1 -3 4 -1 2 1 -5 4\n**Output:** 6","correct_answer":"","starter_code":"nums = list(map(int, input().split()))\n\ndef max_subarray(nums):\n    # Write your solution here\n    pass\n\nprint(max_subarray(nums))","test_cases":[{"input":"-2 1 -3 4 -1 2 1 -5 4","expected":"6"},{"input":"1","expected":"1"},{"input":"-1 -2 -3","expected":"-1"}],"tags":["dp","hard"]},
    {"category":"coding","difficulty":"medium","question_text":"## Second Largest\nFind the second largest number.\n\n**Input:** 12 35 1 10 34 1\n**Output:** 34","correct_answer":"","starter_code":"nums = list(map(int, input().split()))\n\ndef second_largest(nums):\n    # Write your solution here\n    pass\n\nprint(second_largest(nums))","test_cases":[{"input":"12 35 1 10 34 1","expected":"34"},{"input":"1 2","expected":"1"},{"input":"5 5 5 4","expected":"4"}],"tags":["arrays","medium"]},
    {"category":"coding","difficulty":"medium","question_text":"## Find Duplicates\nFind all duplicate numbers. Print sorted space-separated. If none print None.\n\n**Input:** 4 3 2 7 8 2 3 1\n**Output:** 2 3","correct_answer":"","starter_code":"nums = list(map(int, input().split()))\n\ndef find_duplicates(nums):\n    # Write your solution here\n    pass\n\nresult = find_duplicates(nums)\nif result:\n    print(*sorted(result))\nelse:\n    print('None')","test_cases":[{"input":"4 3 2 7 8 2 3 1","expected":"2 3"},{"input":"1 2 3","expected":"None"}],"tags":["arrays","medium"]},
    {"category":"coding","difficulty":"hard","question_text":"## Anagram Check\nCheck if two strings are anagrams. Print True or False.\nLine 1: first string, Line 2: second\n\n**Input:** listen / silent\n**Output:** True","correct_answer":"","starter_code":"s1 = input().strip().lower()\ns2 = input().strip().lower()\n\ndef is_anagram(s1, s2):\n    # Write your solution here\n    pass\n\nprint(is_anagram(s1, s2))","test_cases":[{"input":"listen\nsilent","expected":"True"},{"input":"hello\nworld","expected":"False"}],"tags":["strings","hard"]},
    {"category":"coding","difficulty":"easy","question_text":"## Count Words\nCount number of words in sentence.\n\n**Input:** Hello World how are you\n**Output:** 5","correct_answer":"","starter_code":"s = input()\n\ndef count_words(s):\n    # Write your solution here\n    pass\n\nprint(count_words(s))","test_cases":[{"input":"Hello World how are you","expected":"5"},{"input":"Python","expected":"1"}],"tags":["strings","easy"]},
    {"category":"coding","difficulty":"medium","question_text":"## FizzBuzz\n1 to N. Multiples of 3=Fizz, 4=Buzz, both=FizzBuzz.\n\n**Input:** 15\n**Output:** 1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz","correct_answer":"","starter_code":"n = int(input())\nresult = []\nfor i in range(1, n + 1):\n    # Write your solution here\n    pass\nprint(*result)","test_cases":[{"input":"15","expected":"1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz"},{"input":"3","expected":"1 2 Fizz"}],"tags":["loops","medium"]},
]

COMPANY_QUESTIONS = [
    {"company":"tcs","category":"quantitative","difficulty":"medium","question_text":"TCS NQT: Train 250m long passes platform 350m long in 60s. Speed in km/h?","options":["30","36","40","42"],"correct_answer":"36","explanation":"Speed=(250+350)/60=10m/s=36km/h","tags":["tcs"],"year":2023},
    {"company":"tcs","category":"logical","difficulty":"easy","question_text":"TCS: Next in series: 5, 10, 20, 40, ?","options":["60","70","80","90"],"correct_answer":"80","explanation":"x2 each. 40x2=80","tags":["tcs"],"year":2023},
    {"company":"tcs","category":"quantitative","difficulty":"easy","question_text":"TCS Digital: CI on 12000 at 10% for 2 years?","options":["2400","2520","2640","2760"],"correct_answer":"2520","explanation":"12000x[(1.1)^2-1]=2520","tags":["tcs"],"year":2023},
    {"company":"tcs","category":"quantitative","difficulty":"hard","question_text":"TCS Ninja: A does work in 24 days, B in 36. Together 6 days then B alone. Total days?","options":["21","24","27","30"],"correct_answer":"27","explanation":"Together 6 days: 5/12 done. B alone: 7/12x36=21. Total=27","tags":["tcs"],"year":2023},
    {"company":"infosys","category":"quantitative","difficulty":"medium","question_text":"Infosys: Boys:Girls=3:2. 5 more boys join, ratio=2:1. Total originally?","options":["20","25","30","35"],"correct_answer":"25","explanation":"(3x+5)/2x=2 -> x=5. Total=25","tags":["infosys"],"year":2023},
    {"company":"infosys","category":"logical","difficulty":"medium","question_text":"Infosys: Ravi is 15th from left, 16th from right. Total people?","options":["28","29","30","31"],"correct_answer":"30","explanation":"15+16-1=30","tags":["infosys"],"year":2023},
    {"company":"infosys","category":"quantitative","difficulty":"medium","question_text":"Infosys: 40 students avg=80. Top 10 avg=90, bottom 10 avg=70. Middle 20 avg?","options":["78","80","82","85"],"correct_answer":"80","explanation":"Middle=1600/20=80","tags":["infosys"],"year":2023},
    {"company":"wipro","category":"quantitative","difficulty":"easy","question_text":"Wipro NLTH: Next prime after 97?","options":["99","101","103","107"],"correct_answer":"101","explanation":"101 is prime","tags":["wipro"],"year":2023},
    {"company":"wipro","category":"logical","difficulty":"medium","question_text":"Wipro: BIRD:CAGE :: CRIMINAL:?","options":["Police","Jail","Law","Court"],"correct_answer":"Jail","explanation":"Bird in Cage; Criminal in Jail","tags":["wipro"],"year":2023},
    {"company":"zoho","category":"quantitative","difficulty":"hard","question_text":"Zoho: HCF=8, LCM=192. One number=64. Find other?","options":["16","24","32","48"],"correct_answer":"24","explanation":"axb=8x192=1536. b=1536/64=24","tags":["zoho"],"year":2023},
    {"company":"accenture","category":"quantitative","difficulty":"easy","question_text":"Accenture: Room 15mx12m. Cost at 35 per sq.m?","options":["6200","6300","6400","6500"],"correct_answer":"6300","explanation":"180x35=6300","tags":["accenture"],"year":2023},
    {"company":"accenture","category":"logical","difficulty":"medium","question_text":"Accenture: Ways to arrange letters of LEADER?","options":["360","720","1440","2880"],"correct_answer":"360","explanation":"6!/2!=360","tags":["accenture"],"year":2023},
    {"company":"cognizant","category":"quantitative","difficulty":"medium","question_text":"CTS: Pipe fills in 20 min, empties in 30 min. Both open. Time to fill?","options":["50","55","60","65"],"correct_answer":"60","explanation":"1/20-1/30=1/60. Time=60 min","tags":["cognizant"],"year":2023},
    {"company":"hcl","category":"quantitative","difficulty":"medium","question_text":"HCL: A=15 days, B=20 days, C=30 days. All together?","options":["5","6","7","8"],"correct_answer":"7","explanation":"9/60=3/20. Days approx 7","tags":["hcl"],"year":2023},
    {"company":"hcl","category":"logical","difficulty":"medium","question_text":"HCL: 6, 13, 25, 51, 101, ?","options":["201","203","205","207"],"correct_answer":"203","explanation":"x2+1, x2-1 pattern: 101x2+1=203","tags":["hcl"],"year":2023},
    {"company":"techmahindra","category":"quantitative","difficulty":"medium","question_text":"TechM: Price falls 20%. Consumption increase to maintain same expenditure?","options":["20%","22%","25%","30%"],"correct_answer":"25%","explanation":"20/80x100=25%","tags":["techmahindra"],"year":2023},
    {"company":"techmahindra","category":"logical","difficulty":"easy","question_text":"TechM: Odd one out: Pen, Pencil, Paper, Book, Rubber","options":["Pen","Pencil","Book","Rubber"],"correct_answer":"Book","explanation":"Book is not a writing instrument","tags":["techmahindra"],"year":2022},
]


def seed_database():
    create_tables()
    db = SessionLocal()
    try:
        if db.query(Question).count() == 0:
            for q in QUANT + LOGICAL + CODING:
                db.add(Question(**q))
            db.commit()
            print(f"Seeded {len(QUANT)+len(LOGICAL)+len(CODING)} questions")
        else:
            print("Questions already seeded")

        if db.query(CompanyQuestion).count() == 0:
            for q in COMPANY_QUESTIONS:
                db.add(CompanyQuestion(**q))
            db.commit()
            print(f"Seeded {len(COMPANY_QUESTIONS)} company questions")
        else:
            print("Company questions already seeded")
    except Exception as e:
        print(f"Seed error: {e}")
        db.rollback()
    finally:
        db.close()
